import "./globals.css";
import ContextProvider from "@/providers/ContextProvider";
import Header from "@/components/Header/Header";
import PromtBox from "@/components/PromtBox/PromtBox";
import SideBar from "@/components/SideBar/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FakeGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ContextProvider>
          <div className="flex items-center justify-between h-screen">
            {/* sidebar */}
            <SideBar />

            <div className="flex flex-col justify-between items-center overflow-hidden w-full bg-[#212121] h-[100vh]">
              <Header />
              {children}
              <PromtBox />
            </div>

          </div>
        </ContextProvider>

      </body>
    </html>
  );
}
